// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX0ODjs9F8aiZDcddFl8nfjVW3dcHOU3M',
    appId: '1:357014774233:web:6f3dde3e42646c8f2679c8',
    messagingSenderId: '357014774233',
    projectId: 'conversify-88c3a',
    authDomain: 'conversify-88c3a.firebaseapp.com',
    storageBucket: 'conversify-88c3a.appspot.com',
    measurementId: 'G-S09F1NGMVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoabmxCw3DXR1c3T1wxPavkp__pccCXvc',
    appId: '1:357014774233:android:ae807b418db85d432679c8',
    messagingSenderId: '357014774233',
    projectId: 'conversify-88c3a',
    storageBucket: 'conversify-88c3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKGV__7Cib1D6vbDSPH5KhG4wgt1fOZnU',
    appId: '1:357014774233:ios:906ef6f3323ed0d92679c8',
    messagingSenderId: '357014774233',
    projectId: 'conversify-88c3a',
    storageBucket: 'conversify-88c3a.appspot.com',
    iosBundleId: 'com.example.conversify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKGV__7Cib1D6vbDSPH5KhG4wgt1fOZnU',
    appId: '1:357014774233:ios:53e05e6778b5a9492679c8',
    messagingSenderId: '357014774233',
    projectId: 'conversify-88c3a',
    storageBucket: 'conversify-88c3a.appspot.com',
    iosBundleId: 'com.example.conversify.RunnerTests',
  );
}
